import {
  STAG_BASE_URL,
  STAG_CONFIG_TYPE,
  STAG_VERSION,
  STAG_CREDENTIALS,
  PRE_PROD_BASE_URL,
  PRE_PROD_CONFIG_TYPE,
  PRE_PROD_VERSION,
  PRE_PROD_CREDENTIALS,
  PROD_BASE_URL,
  PROD_CONFIG_TYPE,
  PROD_VERSION,
  PROD_CREDENTIALS,
  WEB_PROD_BASE_URL,
  WEB_STAG_BASE_URL,
  WEB_PRE_PROD_BASE_URL,
  TERMS_CONDITION_URL,
  PRIVACY_POLICY_URL,
  REVERSE_GEOCODING_URL,
  PLACES_TEXT_SEARCH_URL,
  GOOGLE_API_KEY,
  STATIC_MAP_URL,
  MAP_API_KEY,
  APP_VERSION,
  BUILD_NUMBER,
  API_VERSION,
  APP_STORE_LINK,
  PLAY_STORE_LINK,
  SITE_KEY,
  DATABASE_VERSION,
  STAG_DEEPLINK_URL_RELEASE,
  STAG_DEEPLINK_URL_DEBUG,
  PRE_DEEPLINK_URL_RELEASE,
  PRE_DEEPLINK_URL_DEBUG,
  PROD_DEEPLINK_URL_RELEASE,
  PROD_DEEPLINK_URL_DEBUG,
} from '@env';

const stagEnvironmentVariables = {
  baseUrl: STAG_BASE_URL,
  configType: STAG_CONFIG_TYPE,
  version: STAG_VERSION,
  credentials: STAG_CREDENTIALS,
  termsAndConditionUrl: WEB_STAG_BASE_URL + TERMS_CONDITION_URL,
  privacyPolicyUrl: WEB_STAG_BASE_URL + PRIVACY_POLICY_URL,
  reverseGeocodingUrl: REVERSE_GEOCODING_URL,
  placesTextSearchUrl: PLACES_TEXT_SEARCH_URL,
  googleApiKey: GOOGLE_API_KEY,
  staticMapUrl: STATIC_MAP_URL,
  mapApiKey: MAP_API_KEY,
  appVersion: APP_VERSION,
  buildNumber: BUILD_NUMBER,
  apiVersion: API_VERSION,
  appStoreLink: APP_STORE_LINK,
  playStoreLink: PLAY_STORE_LINK,
  siteKey: SITE_KEY,
  databaseVersion: DATABASE_VERSION,
  downloadUrl: WEB_STAG_BASE_URL,
  deepLinkUrlRelease: STAG_DEEPLINK_URL_RELEASE,
  deepLinkUrlDebug: STAG_DEEPLINK_URL_DEBUG,
};

const preProdEnvironmentVariables = {
  baseUrl: PRE_PROD_BASE_URL,
  configType: PRE_PROD_CONFIG_TYPE,
  version: PRE_PROD_VERSION,
  credentials: PRE_PROD_CREDENTIALS,
  termsAndConditionUrl: WEB_PRE_PROD_BASE_URL + TERMS_CONDITION_URL,
  privacyPolicyUrl: WEB_PRE_PROD_BASE_URL + PRIVACY_POLICY_URL,
  reverseGeocodingUrl: REVERSE_GEOCODING_URL,
  placesTextSearchUrl: PLACES_TEXT_SEARCH_URL,
  googleApiKey: GOOGLE_API_KEY,
  staticMapUrl: STATIC_MAP_URL,
  mapApiKey: MAP_API_KEY,
  appVersion: APP_VERSION,
  buildNumber: BUILD_NUMBER,
  apiVersion: API_VERSION,
  appStoreLink: APP_STORE_LINK,
  playStoreLink: PLAY_STORE_LINK,
  siteKey: SITE_KEY,
  databaseVersion: DATABASE_VERSION,
  downloadUrl: WEB_PRE_PROD_BASE_URL,
  deepLinkUrlRelease: PRE_DEEPLINK_URL_RELEASE,
  deepLinkUrlDebug: PRE_DEEPLINK_URL_DEBUG,
};

const prodEnvironmentVariables = {
  baseUrl: PROD_BASE_URL,
  configType: PROD_CONFIG_TYPE,
  version: PROD_VERSION,
  credentials: PROD_CREDENTIALS,
  termsAndConditionUrl: WEB_PROD_BASE_URL + TERMS_CONDITION_URL,
  privacyPolicyUrl: WEB_PROD_BASE_URL + PRIVACY_POLICY_URL,
  reverseGeocodingUrl: REVERSE_GEOCODING_URL,
  placesTextSearchUrl: PLACES_TEXT_SEARCH_URL,
  googleApiKey: GOOGLE_API_KEY,
  staticMapUrl: STATIC_MAP_URL,
  mapApiKey: MAP_API_KEY,
  appVersion: APP_VERSION,
  buildNumber: BUILD_NUMBER,
  apiVersion: API_VERSION,
  appStoreLink: APP_STORE_LINK,
  playStoreLink: PLAY_STORE_LINK,
  siteKey: SITE_KEY,
  databaseVersion: DATABASE_VERSION,
  downloadUrl: WEB_PROD_BASE_URL,
  deepLinkUrlRelease: PROD_DEEPLINK_URL_RELEASE,
  deepLinkUrlDebug: PROD_DEEPLINK_URL_DEBUG,
};

export default prodEnvironmentVariables;
