export default {
  // Platform
  PLATFORM_ANDROID: 'android',
  PLATFORM_IOS: 'ios',
  // Storage
  KEY_USER: 'UserDetails',
  ASYNC_LANG: 'LangSelected',
  USER_TOKEN: 'UserToken',
  IS_DIRECT_LOGIN: 'isDirectLogin',
  CLEAR_STORAGE: 'clearStorage',
  SAFETAPP_BUILDNO: 'safeTappBuildNo',
  RESET_BUILDNO: 10024,
  VERSION_IGNORE: 'isVersionIgnored',
  LAST_BUILD_NO: 'lastBuildNo',
  SSO_LOGIN_HISTORY: 'ssoLoginHistory',
  APP_REVIEW_STATUS: 'AppReviewStatus',
  SET_DIRECT_LOGIN: 'setDIrectLogin',
  LAST_API_LOG_TIME: 'lastApiLogTime',
  DATABASE_VERSION: 'databaseVersion',
  INCOMPLETE_FORM_WARNING: 'incompleteFormWarning',
  FORM_LOCAL_DATA: 'formLocalData',
  // Stack Type
  SPLASH_STACK: 'SplashStack',
  AUTH_STACK: 'AuthStack',
  APP_STACK: 'AppStack',
  MAINTENANCE_STACK: 'MaintenanceStack',
  // Navigation
  DRAWER_STACK: 'Drawer',
  TAB_STACK: 'Tab',
  HOME_STACK: 'HomeStack',
  // Page Navigation
  PAGE_SPLASH: 'Splash',
  PAGE_SPLASH_MAINTENANCE: 'SplashMaintenance',
  PAGE_LOGIN: 'Login',
  PAGE_FORGOT_PASSWORD: 'ForgotPassword',
  PAGE_HELP: 'Help',
  PAGE_HELP_STACK: 'HelpStack',
  PAGE_CREATE_ACCOUNT: 'CreateAccount',
  PAGE_COMPANY_SELECTION: 'CompanySelection',
  PAGE_SSO_LOGIN: 'SsoLogin',
  PAGE_WEBVIEW_SCREEN: 'WebviewScreen',
  PAGE_HOME: 'Home',
  PAGE_PROFILE: 'Profile',
  PAGE_PROFILE_STACK: 'ProfileStack',
  PAGE_LANGUAGE: 'Language',
  PAGE_LANGUAGE_STACK: 'LanguageStack',
  PAGE_DRIVER_COMPLIANCE: 'DriverCompliance',
  PAGE_DRIVER_COMPLIANCE_STACK: 'DriverComplianceStack',
  PAGE_DRIVER_COMPLIANCE_UPLOAD: 'DriverComplianceUpload',
  PAGE_WORKING_ALONE_SETTINGS: 'WorkingAloneSettings',
  PAGE_WORKING_ALONE_SETTINGS_STACK: 'WorkingAloneSettingsStack',
  PAGE_SWITCH_ACCOUNT: 'SwitchAccount',
  PAGE_SWITCH_ACCOUNT_STACK: 'SwitchAccountStack',
  PAGE_VERIFICATION: 'Verification',
  PAGE_VERIFICATION_STACK: 'VerificationStack',
  PAGE_CERTIFICATE_UPLOAD: 'CertificateUpload',
  PAGE_OPEN_FORM: 'OpenForm',
  PAGE_OPEN_FORM_STACK: 'OpenFormStack',
  PAGE_UPLOAD_STACK: 'UploadStack',
  PAGE_COURSE_COMPLETE: 'CourseComplete',
  PAGE_COURSE_COMPLETE_STACK: 'CourseCompleteStack',
  PAGE_COURSE_START: 'CourseStart',
  PAGE_FORMS: 'Forms',
  PAGE_FORMS_STACK: 'FormsStack',
  PAGE_FOLDERS: 'Folders',
  PAGE_FOLDERS_STACK: 'FoldersStack',
  PAGE_ASSETS: 'Assets',
  PAGE_ASSETS_STACK: 'AssetsStack',
  PAGE_ASSET_LIST: 'AssetList',
  PAGE_ASSET_FORMS: 'AssetForms',
  PAGE_TEAM: 'Team',
  PAGE_TEAM_STACK: 'TeamStack',
  PAGE_TEAM_USER: 'TeamUser',
  PAGE_TEAM_USER_DETAILS: 'TeamUserDetails',
  PAGE_SCANNER: 'Scanner',
  PAGE_SCANNER_STACK: 'ScannerStack',
  PAGE_FORM_DETAILS: 'FormDetails',
  PAGE_HOME_MENU: 'HomeMenu',
  PAGE_HOME_ASSIGNED: 'HomeAssigned',
  PAGE_HOME_IN_PROGRESS: 'HomeInProgress',
  PAGE_HOME_REQUIRED: 'HomeRequired',
  PAGE_HOME_RECOMMENDED: 'HomeRecommended',
  PAGE_REQUIRED_DETAILS: 'RequiredDetails',
  PAGE_HOME_COMPLETED: 'HomeCompleted',
  PAGE_HOME_TASK: 'HomeTask',
  PAGE_HOME_TASK_DETAILS: 'HomeTaskDetails',
  PAGE_SIGNATURE_DETAILS: 'SignatureDetails',
  PAGE_FOLDERS_LIST: 'FoldersList',
  PAGE_UPLOAD_TRAINING: 'UploadTraining',
  PAGE_FAQ: 'Faq',
  PAGE_WORKING_ALONE: 'WorkingAlone',
  PAGE_WORKING_ALONE_STACK: 'WorkingAloneStack',
  PAGE_OFFLINE_PENDING_FORMS: 'OfflinePendingForms',
  PAGE_VIEWPROFILE: 'ViewProfile',
  PAGE_ASSET_SCANNER: 'AssetScannner',
  PAGE_EPUBREADER: 'EpubReader',
  PAGE_MAINTENANCE: 'MaintenancePage',
  // Page Name
  PAGE_NAME_FORGOT_PASSWORD:
    'SafeTappV2_ForgotPassword.lblForgetPasswordHeader',
  PAGE_NAME_HELP: 'SafeTappV2_Help.lblHelpHeader',
  PAGE_NAME_CREATE_ACCOUNT: 'SafeTappV2_CreateAccount.lblCreateAccountHeader',
  PAGE_NAME_COMPANY_SELECTION: 'PAGE_COMPANY_SELECTION',
  PAGE_NAME_SSO_LOGIN: 'PAGE_SSO_LOGIN',
  PAGE_NAME_PROFILE: 'SafeTappV2_Profile.lblProfileHeader',
  PAGE_NAME_DRIVER_COMPLIANCE:
    'SafeTappV2_DriverCompliance.lblDriverComplianceSentence',
  PAGE_NAME_SWITCH_ACCOUNT: 'SafeTappV2_SideMenu.lblSwitchAccountSentence',
  PAGE_NAME_VERIFICATION: 'PAGE_VERIFICATION',
  PAGE_NAME_CERTIFICATE_UPLOAD:
    'SafeTappV2_CertificateUpload.lblCertificateUpload',
  PAGE_NAME_HOME: 'SafeTappV2_SideMenu.lblHomeSentence',
  PAGE_NAME_FORMS: 'SafeTappV2_Forms.lblFormsHeader',
  PAGE_NAME_FOLDERS: 'SafeTappV2_Folders.lblFoldersHeader',
  PAGE_NAME_ASSETS: 'SafeTappV2_Assets.lblAssetsHeader',
  PAGE_NAME_TEAM: 'SafeTappV2_MyTeam.lblTeamSentence',
  PAGE_NAME_SCANNER: 'SafeTappV2_Scanner.lblScannerHeader',
  PAGE_NAME_LANGUAGE: 'SafeTappV2_Login.lblLanguageSentence',
  PAGE_NAME_INCOMPLETE_FORMS: 'SafeTappV2_Forms.lblFailedPendingFormsSentence',
  // API Response
  API_SUCCESS: '',
  API_FAILURE: '',
  API_TOKEN_EXPIRED: 'Signature verification failed: Token expired',
  API_DUPLICATE_LOGIN: 'User logged in elsewhere. Login again.',
  API_MISSING_TOKEN: 'No access token provided',
  API_PASSWORD_CHANGED: 'Password changed. Login again.',
  API_TIMEOUT: 'timeout of 20000ms exceeded',
  API_TIMEOUT_ERR_MESSAGE: 'SafeTappV2_Login.lblPoorConnectionSentence',
  API_NO_NETWORK_MESSAGE: 'SafeTappV2_Forms.lblNoNetworkSentence',
  API_NETWORK_ERROR_CODE: 'ERR_NETWORK',
  API_INTERNAL_SERVER_ERROR_MSG: 'Internal Server Error',
  API_INVALID_DATA: 'Invalid data',
  //File
  FILE_NOT_SUPPORT: 'No app associated for supporting this document format',
  FILE_SUPPORT_IOS: 'Error: The Internet connection appears to be offline.',
  FILE_SUPPORT_ANDROID_MSG1: 'Error: Unable to resolve host "',
  FILE_SUPPORT_ANDROID_MSG2: '": No address associated with hostname',
  // Common
  EMPTY_STRING: '',
  EMPTY_ARRAY: [],
  EMPTY_OBJECT: {},
  STORAGE: 'storage',
  CAMERA: 'camera',
  LOCATION: 'location',
  //Push notifications types
  NOTIFICATION_TYPE_FORMS: 'forms',
  // Epub Async Data key
  EPUB_MYLOCATION: 'myLocation',
  EPUB_MYFONT: 'myFont',
  EPUB_MYBGTHEME: 'myBgTheme',
  EPUB_SAMEFILE: 'sameFile',
  EPUB_MYLOCATIONCFI: 'myLocationCfi',
  //MFA
  MFA_DEVICE_KEY: 'mfaTrustedDeviceKey',
  SORT_STATUS_FORM: 'formStatus',
  SORT_SORTBY_FORM: 'formSortBy',
  DEEPLINK: 'DEEPLINK',
};
